### ISSUE TITLE
Make the HAMT a standalone module that can be used by other libraries

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-unixfs-importer#1]
Pretty please 🥺🙏🏽

**Comment by achingbrain** [comment]
Is there any reason we didn't use https://github.com/mattbierner/hamt or https://github.com/mattbierner/hamt_plus?

**Comment by daviddias** [comment]
Didn't know about those. We made the JS HAMT way after the GO HAMT

**Comment by achingbrain** [comment]
Shame they got the good name on npm already!

**Comment by mikeal** [comment]
Which HAMT encoding are we using? The current one in the dag-pb based unixfs or the one Filecoin is using and, I assume, unixfs-v2 will use https://github.com/ipfs/go-hamt-ipld ?

**Comment by achingbrain** [comment]
This module uses [hamt-sharding](https://github.com/ipfs-shipyard/js-hamt-sharding) which was extracted from the js-unixfs-engine module and is a vanilla HAMT.

I hadn't seen `go-hamt-ipld` but it looks like it uses a CHAMP style HAMT which might or [might not](https://groups.google.com/d/msg/clojure/zO-5yUx2aSk/LhiPZj5tCQAJ) be an improvement.

For `unixfs-v2` do you know if anyone's done any real-world benchmarks to compare the performance? If not it's probably something we should look at.
