### ISSUE TITLE
Write file chunks in parallel

### ISSUE THREAD

**Issue by achingbrain** [ipfs/js-ipfs-unixfs-importer#9]
We should write leaf nodes to disk in parallel to increase performance.

I think [this](https://github.com/ipfs/js-ipfs-unixfs-importer/blob/master/src/builder/builder.js#L138-L153) is the `pull-streams/throughs/async-map` that needs turning into a `pull-paramap`.

**Comment by achingbrain** [comment]
Should be the solution to point 3 in ipfs/js-ipfs#1785

**Comment by mcollina** [comment]
+1!
